Revert "aws-cli: Update to version 1.36.15"
This reverts commit 4854a002228adf15cdf4ef5de9c10911385300c4.

This fails running with this message:

Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python3.10/site-packages/awscli/clidriver.py", line 73, in main
    driver = create_clidriver()
  File "/usr/lib/python3.10/site-packages/awscli/clidriver.py", line 82, in create_clidriver
    load_plugins(
  File "/usr/lib/python3.10/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/lib/python3.10/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/lib/python3.10/site-packages/awscli/handlers.py", line 106, in <module>
    from awscli.customizations.s3.s3 import s3_plugin_initialize
  File "/usr/lib/python3.10/site-packages/awscli/customizations/s3/s3.py", line 15, in <module>
    from awscli.customizations.s3.subcommands import ListCommand, WebsiteCommand, \
  File "/usr/lib/python3.10/site-packages/awscli/customizations/s3/subcommands.py", line 18, in <module>
    from botocore.utils import is_s3express_bucket, ensure_boolean
ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/usr/lib/python3.10/site-packages/botocore/utils.py)

Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>