diffutils: Update to 3.7
- Update from 3.6 to 3.7
- No update of rootfile required
- Changelog
   2018-12-31  Jim Meyering  <meyering@fb.com>
	version 3.7
	* NEWS: Record release date.
	maint: distribute new file, init.cfg
	Otherwise, strip-trailing-cr would fail on a system without valgrind.
	* tests/Makefile.am (EXTRA_DIST): Include init.cfg.
   2018-12-30  Dennis Lambe Jr  <malsyned@malsyned.net>
	diff: adjust ANSI escapes for compatibility with less -R
	GNU less can display ANSI-colored text with the -R flag, but this
	support has some limitations. One of them is that if an escape
	sequence starts on one line and ends on a different line, only the
	first line will be colored in less.
	As a result, when diff creates colored output with multi-line deletes
	or adds, less will only color the first line.
	This change resets ANSI color to the default at the end of
	each line and restarts it at the beginning of the next. It patches
	normal and context mode. Side-by-side already worked in my testing.
	* src/context.c (print_context_label, pr_context_hunk): As above.
	(pr_unidiff_hunk, print_context_header): Likewise.
	* src/normal.c (print_normal_hunk): Likewise.
	* tests/colors: Adjust existing tests to accommodate this.
	* NEWS (Improvements): Mention it.
	Proposed in http://bugs.gnu.org/31105
   2018-12-29  Jim Meyering  <meyering@fb.com>
	tests: fix colors test on systems lacking fractional timestamp support
	* tests/colors: The .NNNNNNNNN suffix is not printed on some systems.
	Adapt the test to accommodate those systems.
	tests: strip-trailing-cr: avoid failure with ASAN
	Valgrind cannot operate on an ASAN-compiled binary.
	* tests/strip-trailing-cr (valgrind): Define as no-op when diff
	was compiled with sanitizer support.
   2018-12-28  Jim Meyering  <meyering@fb.com>
	tests: add test for --strip-trailing-cr UMR bug
	* tests/strip-trailing-cr: New file. Test for today's bug fix.
	* tests/Makefile.am (TESTS): Add it.
	tests: import test infrastructure from coreutils
	* tests/init.cfg: New file, for require_valgrind_ definition (from coreutils).
	* tests/Makefile.am (PATH): Don't set stderr_fileno_ here, since it is
	now initialized in init.cfg.
   2018-12-28  Paul Eggert  <eggert@cs.ucla.edu>
	    Jim Meyering  <jim@meyering.net>
	diff: fix UMR with --strip-trailing-cr
	Problem reported by Hongxu Chen (Bug#31935).
	* src/io.c (prepare_text): Strip trailing CR before
	doing the rest of the analysis.
	* NEWS: Mention the fix.
   2018-12-28  Bruno Haible  <bruno@clisp.org>
	tests: colors: avoid test failure on AIX 7
	* tests/colors: Splice the argument into the printf format string.
   2018-12-27  Bruno Haible  <address@hidden>
	maint: don't use an undocumented Autoconf macro
	* configure.ac: Use AC_CONFIG_HEADERS instead of AC_CONFIG_HEADER.
   2018-12-23  Jim Meyering  <meyering@fb.com>
	build: avoid build failure with --enable-gcc-warnings and latest gcc
	* src/diff.c (usage): Assert that each line length is no longer than
	the minimum required size of 4095.  This lets newer gcc (currently
	9.0.0 20181219) infer that it need not issue this warning:
	diff.c:1012:19: error: '%.*s' directive output between 0 and 2147483647
	bytes may exceed minimum required size of 4095
	[-Werror=format-overflow=]
	1012 |        printf ("  %.*s", msglen, msg);
	build: update gnulib to latest; and bootstrap and init.sh
	build: make the autoconf-2.63 requirement explicit
	* configure.ac: AC_PREREQ: Require 2.63, not 2.59. And quote properly.
	Autoconf-2.63 has been required for some time via gnulib.
	This merely makes it explicit.
   2018-12-20  Jim Meyering  <meyering@fb.com>
	maint: use https: in gnu mirror URL prefix, not http
	This appears in the generated release announcement message.
	* cfg.mk (url_dir_list): Use https: prefix, not http:.
   2018-07-24  Paul Eggert  <eggert@cs.ucla.edu>
	cmp: fix bug in -b diagnostic
	Problem reported by mancha (Bug#32249).
	* src/cmp.c (count_newlines): Restore old value of sentinel.
	* tests/cmp: Test for the bug.
	build: update gnulib submodule to latest
   2018-05-14  Paul Eggert  <eggert@cs.ucla.edu>
	doc: prepend "GNU" to NAME in man pages
	Requested by RMS.
	* src/cmp.c, src/diff.c, src/diff3.c, src/sdiff.c:
	Prepend "GNU" to first comment, so that the man page says "GNU".
   2018-04-20  Paul Eggert  <eggert@cs.ucla.edu>
	sdiff: port to mingw
	Problem reported by Ross Burton (Bug#31218).
	* src/sdiff.c (checksigs): Use ‘raise’, not ‘kill’.
   2018-03-23  Paul Eggert  <eggert@cs.ucla.edu>
	build: update gnulib submodule to latest
   2018-01-14  Jim Meyering  <meyering@fb.com>
	tests: fix quoting error in previous change
	* tests/colors: Double-quote $PATH.
   2018-01-06  Jim Meyering  <meyering@fb.com>
	tests: port tests/colors to some env-munging shell
	* tests/colors: Also set PATH="$PATH" in env invocation.
	maint: update gnulib and copyright dates for 2018
	* gnulib: Update to latest.
	* all files: Run "make update-copyright".
	* bootstrap: Update from gnulib.
	maint: suppress gcc's new -Wcast-function-type in gnulib
	* configure.ac (WERROR_CFLAGS): Suppress gcc's new -Wcast-function-type
	warning in gnulib, because it would trigger on this:
	sig-handler.h:47:12: error: cast between incompatible function types\
	  from 'void (* const)(int,  siginfo_t *, void *)' \
	  {aka 'void (* const)(int,  struct <anonymous> *, void *)'} \
	  to 'void (*)(int)' [-Werror=cast-function-type]
	return (sa_handler_t) a->sa_sigaction;
   2017-10-22  Jim Meyering  <meyering@fb.com>
	tests: add expected-failing test for minor subopimality
	In some unusual cases, diff -u prints suboptimal output.
	* tests/large-subopt: New test script.
	* tests/Makefile.am (TESTS): Add it.
	(XFAIL_TESTS): Add it here, too, to record that this test is
	currently expected to fail.
	* tests/large-subopt.in1, tests/large-subopt.in2: Inputs derived from
	those in http://bugs.gnu.org/28796
   2017-09-23  Jim Meyering  <meyering@fb.com>
	gnulib: update to latest
   2017-05-21  Jim Meyering  <meyering@fb.com>
	maint: make the announcement template Cc the devel- list
	* cfg.mk (announcement_Cc_): Define.
	maint: post-release administrivia
	* NEWS: Add header line for next release.
	* .prev-version: Record previous version.
	* cfg.mk (old_NEWS_hash): Auto-update.

Signed-off-by: Adolf Belka <adolf.belka@ipfire.org>
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>