rust 1.65 won't build if 'Cargo.toml.orig' is present in one of the crate files
Please see the discussions about this patch series here:

https://lists.ipfire.org/pipermail/development/2022-November/014714.html

and here:

https://lists.ipfire.org/pipermail/development/2022-November/014887.html

During building 'rust 1.65', I always got:

...
error: invalid inclusion of reserved file name Cargo.toml.orig in
package source
...
[Build stops]

After a rather frustrating while, I decided to delete this file during building the particular crate file.

Fun! Building completed without errors.

For now, I added an appropriate if-statement in each crate file which contains 'Cargo.toml.orig'.
If 'Cargo-toml.orig' is present: delete it. Just throw it away.

It might be that there is a more elegant way to do this - if 'someone' has a better solution, please
submit an easier patch.

I searched a few days, but didn't find ANY clue what is going on here.

All I can say: building runs. No more errors or breaks. Nothing.

Please test and confirm.

Signed-off-by: Matthias Fischer <matthias.fischer@ipfire.org>