alsa: Update to version 1.2.15.1
- Update from version 1.2.14 to 1.2.15.1
- Update of rootfile
- Changelog
    1.2.15.1
      alsa-lib
	Core
	    ucm: use closefrom instead of close_range
	Use Case Manager API
	    ucm: exec - fix maxfd used warning
	    ucm: use closefrom instead of close_range
	Configuration
	    conf: cards: unify whitespace - use tabs and remove trailing spaces
	    conf: pistachio-card: define pcm configuration block only one time
	    conf: YMF744: define pcm configuration block only one time
	    conf: VX222,VXPocket: define pcm configuration block only one time
	    conf: VIA686A,VIA82xx: define pcm configuration block only one time
	    conf: TRID4DWAVENX: define pcm configuration block only one time
	    conf: SI7018: define pcm configuration block only one time
	    conf: SB-XFi: define pcm configuration block only one time
	    conf: RME96[35][26]: define pcm configuration block only one time
	    conf: PS3: define pcm configuration block only one time
	    conf: PMac,PMacToonie: define pcm configuration block only one time
	    conf: PC-Speaker: define pcm configuration block only one time
	    conf: NFORCE: define pcm configuration block only one time
	    conf: Maestro3: define pcm configuration block only one time
	    conf: Loopback: define pcm configuration block only one time
	    conf: ICH,ICH4,ICH-MODEM: define pcm configuration block only one time
	    conf: ICE17[12][24]: define pcm configuration block only one time
	    conf: HdmiLpeAudio: define pcm configuration block only one time
	    conf: GUS: define pcm configuration block only one time
	    conf: FWSpeakers: define pcm configuration block only one time
	    conf: FM801: define pcm configuration block only one time
	    conf: FireWave: define pcm configuration block only one time
	    conf: ES1968: define pcm configuration block only one time
	    conf: ENS137[01]: define pcm configuration block only one time
	    conf: EMU10K1X: define pcm configuration block only one time
	    conf: EMU10K1: define pcm configuration block only one time
	    conf: Aureon51: define pcm configuration block only one time
	    conf: Echo3G: define pcm configuration block only one time
	    conf: CS46xx: define pcm configuration block only one time
	    conf: CMI8xxx: define pcm configuration block only one time
	    conf: CA0106: define pcm configuration block only one time
	    conf: AU88[123]0: define pcm configuration block only one time
	    conf: Aureon: define pcm configuration block only one time
	    conf: Audigy: define pcm configuration block only one time
	    conf: AACI,ATIIXP: define pcm configuration block only one time
	    conf: vc4-hdmi: define pcm configuration block only one time
	    conf: HDA-Intel: define pcm configuration block only one time
	    conf: USB-Audio: define pcm configuration block only one time
	    Revert "conf: fix load_for_all_cards() - do not merge the card specific
		contents"
	    conf: fix possible memory leak in config_file_open() - error path
	    conf: merge card specific contents per file (whole) after parsing
      alsa-utils
	ALSA Control (alsactl)
	    alsactl: fix build when in subdirectory
	aplay/arecord
	    aplay: add missing break before the default case
      alsa-ucm-conf
	Configuration
	    ucm2: codecs: rt722: add condition to SetLED for mic
	    ucm2: sof-soundwire: Simplify cs42l45 configs
	    sof-soundwire: third fix for multi-codec
    1.2.15
      alsa-lib
	Core
	    include: fix typo in error.h to avoid compile error when gcc <= 2.95
	    include: list.h - add list_splice() and list_splice_init() functions
	    github: add coverity.yml
	    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
	    error: add missing log_priority/interface functions to header file
	    configure: bumb version to 1.2.13pre1 (for alsa-utils)
	    include: remove local SNDMSG/SYSMSG defines (no longer used)
	    huge correction of tabulators and whitespaces
	    log: implement filter based on string configuration (env LIBASOUND_DEBUG).
	    error: add priority and interface strings to the log messages
	    redesign the message log functions
	    error: do not export internal snd_err_msg variable
	    github: fix Fedora workflow (awk package dependency)
	Config API
	    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
	    huge correction of tabulators and whitespaces
	Control API
	    coverity.com fixes - initial round
	    snd_tlv_convert_to_dB: Fix mute handling for MINMAX_MUTE type
	    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
	    huge correction of tabulators and whitespaces
	    redesign the message log functions
	HWDEP API
	    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
	Mixer API
	    mixer: abst - reshuffle snd_mixer_simple_basic_register code to be more
		logical
	    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
	    huge correction of tabulators and whitespaces
	    mixer: bag - fix bag_del_all implementation (missing free)
	Mixer Abstraction API
	    huge correction of tabulators and whitespaces
	PCM API
	    pcm: plugin - avoid 32-bit to 64-bit return value conversions
	    add missing return value changes for snd_config_get_string() calls
	    add missing return value changes for snd_config_get_id() calls
	    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
	    pcm route: suppress false positive warning for gcc 8+
	    pcm: add a loop to snd_pcm_avail_delay() to avoid bogus delay values
	Rawmidi API
	    rawmidi: Fix SNDRV_RAWMIDI_INFO_STREAM_INACTIVE duplicate definition
	    rawmidi: Fix the prefix of the inactive stream flag
	Sequencer API
	    seq: fix snd_seq_drain_output return value for partial drain
	    seq: hw - notify if running mode / pversion ioctl fails
	Topology API
	    add missing return value changes for snd_config_get_id() calls
	    topology: fix nibble warning in tplg_save_quoted()
	Use Case Manager API
	    ucm: add ValueGlobals section to the top configuration file
	    ucm: fix the DefineRegex issue where multiple variables were set to empty
		string
	    ucm: Include directive - add optional behaviour
	    ucm: complete dependency graphs for conflicting/supported device lists
	    ucm: implement DeviceVariant configuration extension
	    ucm: implement ValueDefaults.BootCardGroup and define use
	    ucm: keep original device name for logs
	    ucm: sort devices by priority
	    ucm: doc - add examples for device name with descriptors (colon)
	    ucm: be more restrictive for device name with descriptor
	    ucm: strip device index when the device type is present only one time
	    ucm: add support for device names with colon (':')
	    ucm: normalize device names
	    ucm: add possibility to inline Verb configurations to the main
		configuration file
	    ucm: add Prepend and Append block handling for If conditions (syntax 8+)
	    add missing return value changes for snd_config_get_string() calls
	    ucm: add missing stdbool.h include to ucm_local.h
	    ucm: fix variant issue where variables or macros are overwritten
	    ucm: remove 'error: ' prefix from error messages (duplication)
	    ucm: remove uc_dbg macro and callers
	    ucm: replace uc_error with snd_error calls
	    ucm: add a basic set of trace/debug log calls
	    ucm: use close_range on _GNU_SOURCE
	    Force to use alphasort64() sorting function for Harmony OS
	    ucm: regex: fix the error message (missing argument)
	    Revert "ucm: do not bump syntax version to 8"
	ALSA Server
	    coverity.com fixes - initial round
	    huge correction of tabulators and whitespaces
	    replace SNDMSG,SYSMSG,SNDERR,SYSERR with new log macros
	Async helpers
	    coverity.com fixes - initial round
	    replace SNDMSG,SYSMSG,SNDERR,SYSERR with new log macros
	Configuration
	    coverity.com fixes - initial round
	    add missing return value changes for snd_config_get_string() calls
	    add missing return value changes for snd_config_get_id() calls
	    conf/pistachio: fix syntax
	    config: do not print errno in snd_config_check_hop()
	    redesign the message log functions
	    conf: fix load_for_all_cards() - do not merge the card specific contents
	    conf: fix parse_array_def - merge arrays
	    conf: Revert "conf: fix load_for_all_cards()"
	    conf: fix parse_array_def override code path
	    Force to use alphasort64() sorting function for Harmony OS
	    conf: aliases: add hda-acpi -> HDA-Intel alias
	Documentation
	    doc: add missing include pcm_plugin.h to source files
	    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
	Error handler
	    coverity.com fixes - initial round
	    error: make prio/interface output a bit shorter in default log handler
	    log: implement filter based on string configuration (env LIBASOUND_DEBUG).
	    error: add priority and interface strings to the log messages
	    redesign the message log functions
	    error: do not export internal snd_err_msg variable
	Simple Abstraction Mixer Modules
	    replace SNDMSG,SYSMSG,SNDERR,SYSERR with new log macros
	Test/Example code
	    test: ucm - remove old syntax configuration files (incomplete anyway)
	    test: update midifile library to ANSI C
      alsa-utils
	Core
	    configure: Allow systemd service installation without systemd.pc
	    github: coverity.yml - run at 4am on Sunday
	    github: add coverity.yml (coverity.com) workflow
	    github: CI: add awk package for Fedora to build.yml
	ALSA Control (alsactl)
	    alsactl: fix error message arguments (remove card)
	    alsactl: fix error handling in check_control_cdev()
	    alsactl: ucm: restore controls for other cards in group
	    alsactl: move udev/systemd files to conf subdirectory
	    alsactl: update state file correctly when initialization failed
	    alsactl: fix state restore to handle dynamic user control elements
	    alsactl: add systemd service to handle deferred card initialization
	    alsactl: ucm: add wrestore command and wait_for_card() for boot
		synchronization
	    alsactl: add -Y option to export card states as key=value pairs
	    alsactl: ucm: implement boot parameters and card group sync infrastructure
	    alsactl: free scandir list in snd_card_clean_cfgdir
	    alsactl: add support for new log handler (alsa-lib 1.2.15)
	    alsactl: restore udev rules - fix HDA analog device check
	ALSA RawMidi Utility (amidi)
	    amidi: Ignore inactive MIDI ports as default at listing
	aconnect
	    aconnect: add support for new log handler (alsa-lib 1.2.15)
	alsamixer
	    alsamixer: add support for new log handler (alsa-lib 1.2.15)
	aplay/arecord
	    aplay: reorganize format handling in begin_wave()
	    Revert "aplay: fix S24_LE wav header"
	    alsactl: add support for new log handler (alsa-lib 1.2.15)
	bat (basic audio tester)
	    bat: Fix buffer time configuration
      alsa-ucm-conf
	Configuration
	    USB-Audio: add support for conf.d configurations
	    USB-Audio: Steinberg UR22C - fix capture channels for older firmware
	    USB-Audio: GoXLR: enable detection of beta firmware (25 channels)
	    USB-Audio: Add jack controls for HP Thunderbolt Dock G2
	    ucm2: sof-soundwire: Update cs42l45 JackControls
	    ucm2: IO-Boards: Toradex: aquila: add support
	    ucm2: Qualcomm: fix indentation for TUXEDO Elite 14
	    ucm2: Qualcomm: fix HDMI0 name for TUXEDO Elite 14
	    ucm2: Qualcomm: add TUXEDO Elite 14 support
	    rt713: add mic led support
	    USB-Audio: Add Audient iD14 MK2 support
	    sof-soundwire: second fix for -sdca variants for multi-codec
	    common: led.conf - don't use If.0 blocks
	    common: split.conf - don't use If.0 blocks
	    USB-Audio: Add support for DualSense PS5 controller
	    ucm2: Add setting LED Mode in SetLED macro
	    sof-soundwire: fix for -sdca variants for multi-codec
	    ucm2: rt712: simplify the init settings
	    ucm2: sof-soundwire: support rt713vb codec
	    ucm2: soundwire: cs42l45: Add support for CS42L45 codec
	    ucm2: Add support for MT8196 Rauru Rev0 Chromebook with SOF
	    USB-Audio: fix Steinberg UR22mkII device names
	    ucm2: codecs: rx-macro: add Headset Left enable/disable
	    ucm2: codecs: pm4125: add ucm for codec
	    ucm2: Qualcomm: x1e80100: T14s: add USB DisplayPort playback
	    Qualcomm: qcs615: Add TALOS EVK HiFi config
	    ucm2: Add support for Steinberg UR22mkII
	    ucm2: Qualcomm: Radxa: fix Displayport SectionDevice
	    ucm2: Qualcomm: Add MONACO-EVK HiFi config
	    ucm2: Qualcomm: sa8775p: Move lemans-evk hifi to sa8775p subdir
	    Qualcomm: Kaanapali: Add Kaanapali MTP HiFi config
	    The X1E80100-EVK needs basically the same configuration as
	    ucm2: MediaTek: mt8391-evk: Add alsa-ucm support
	    Add support for RME Fireface UCX (heavily based on RME Fireface UCX II
		config)
	    ucm2: Qualcomm: Add Microsoft Surface Pro 12in config
	    ucm2: Qualcomm: x1e80100: Add X1E001DE-DEVKIT configuration
	    ucm2: Qualcomm: add Radxa Dragon Q6A
	    ucm2: sof-soundwire: add rt721 ucm support
	    ucm2: Qualcomm: add Lenovo Ideapad 5 (Slim 5x / 2in1) support
	    ucm2: Qualcomm: Rename qcs6490-rb3gen2 and qcs9075-iq-evk ucm2 conf
	    ucm2: Qualcomm: Add Dell Latitude 7455 / Inspiron 14 Plus
	    ucm2: codecs: lpass-rx-macro: move mixers that do not belong
	    UR44: Add stereo inputs to the HiFi profile, relabel the inputs and outputs
	    Recognize one more Steinberg UR44 variant
	    ucm2: sof-soundwire: add rt712+rt1320 amplifier
	    ucm2: MediaTek: mt8395-evk: Add support for SOF
	    Behringer UCM204HD/404HD: Fix the macro evaluation for Syntax 7+
	    UCM2: Intel: sof-hda-dsp: HiFi: IPC3 mono DMIC is exposed as stereo PCM
	    codecs/hda/hdmi.conf - add support for zero device
	    ucm2: MediaTek: mt8365-evk: Add SOF support
	    ucm2: USB-Audio: Add Teufel CAGE PRO
	    add MSI MAG B850M Mortar Wifi to USB-Audio.conf
	    ucm2: sof-soundwire: add rt712-vb device
	    UCM2: Intel: sof-hda-dsp: HiFi: Fix handling of mono DMICs
	    ucm2: Qualcomm: Update the HIFI enable mixer commands for qcm6490-idp and
		qcs6490-rb3gen2
	    ucm2: Qualcomm: Update the QCM6490 and QCS6490 hifi conf files
	    Qualcomm: Add QCS9075-IQ-EVK HiFi config
	    Changed 'Stream Mix' channel names to match the latest Window
	    ucm2: Qualcomm: add ASUS Vivobook S 15 support
	    USB-Audio: Added Beacn Mic and Studio Support
	    USB-Audio: Solid State Labs SSL 2 - fix capture channels
	    ucm2: IO-Boards: Toradex: smarc: add support
	    ucm2: USB-Audio: Behringer: Flow8: fix conflicting
	    ucm2: tegra: max98090: fix headphones conflicting device
	    ucm2: Qualcomm: sm8650: QRD: fix headset jack hw mute
	    ucm2: Qualcomm: sc8280xp: fix internal microphones device
	    Fix Presonus Revelator IO44 HWChannels count
	    tegra: max98089: fix cset names
	    ucm2: Qualcomm: Add Surface Laptop 7
	    ucm2: Qualcomm: x1e80100: Also match DMI board name
	    USB-Audio: Solid State Labs SSL 2+ - fix capture channels
	    USB-Audio: Remove useless sections for Solid State Labs SSL 2+
	    acp3x-alc5682-max98357: Fix path of HiFi.conf

Signed-off-by: Adolf Belka <adolf.belka@ipfire.org>
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>