glib: Update to version 2.70.1
- Update from 2.69.0 to 2.70.1
- Update of rootfile
- The internal_pcre otion was removed from glib with the release of 2.69.0
   The build of glib by meson still worked as the missing option was only marked as a
   warning. With the latest meson this missing option was marked as an error and stopped
   the build.
   glib no longer has an internal pcre capability and will always look for the system
   version meaning that the internal_pcre=false is no longer required.
- This update of glib is combined with the meson update so that the combination builds
   without errors.
- Changelog
   Overview of changes in GLib 2.70.1
    * Fix network changes not being signalled from NetworkManager (work by
      Julian Andres Klode) (#2505)
    * Fix build when building with --fatal-meson-warnings (work by Eli Schwartz) (!2304)
    * Bugs fixed:
      - #2505 g_network_monitor_nm never updates on connection change (listens for signal on wrong dbus interface)
      - !2245 gdesktopappinfo: Do not call xterm when it does not exist, inform the caller the launch failed
      - !2253 Backport !2251 “GString: Bump minimum size” to glib-2-70
      - !2256 Backport !2254 “Small optimization for g_object_set” to glib-2-70
      - !2259 Backport !2257 “Fix documentation for g_dbus_object_manager_get_object().” to glib-2-70
      - !2262 Backport !2244 “gutils: Avoid segfault in g_get_user_database_entry” to glib-2-70
      - !2271 Backport !2266 “fix uninitial variable” to glib-2-70
      - !2276 Backport !2274 “Do not try to access errno after calling getpwnam_r.” to glib-2-70
      - !2300 Backport !2285 “fix issues found by svace static code analyzer” to glib-2-70
      - !2301 Backport !2293 “glib-private: Fix MSVC build with AddressSanitizer” to glib-2-70
      - !2302 Backport !2291 “gnetworkmonitornm: Stop using removed PropertiesChanged signal” to glib-2-70
      - !2304 meson: fix warnings for extract_all_objects function
   Overview of changes in GLib 2.70.0
    * Bugs fixed:
      - !2248 ci: Replace FreeBSD 11 with FreeBSD 13
    * Translation updates:
      - Croatian
      - Danish
      - English (United Kingdom)
      - French
      - German
      - Hungarian
      - Polish
      - Swedish
      - Turkish
   Overview of changes in GLib 2.69.3
    * Bugs fixed:
      - #2425 g_settings_schema_key_range_check() misbehaves for int versus bool
      - #2472 Compiling anything with GCC <4.6 spews deprecation warnings
      - #2477 `g_invoke_closure` bindings API break.
      - #2481 GPowerProfileMonitorPortal does not notice initial power-saver-enabled status
      - !2219 doc: Explicitly said, that no null term. is needed
      - !2238 ci: Use C.UTF-8 locale on FreeBSD 12
      - !2240 gio: Fix conditions in memory-monitor test
    * Translation updates:
      - Basque
      - Catalan
      - Chinese (China)
      - Galician
      - Kazakh
      - Korean
      - Lithuanian
      - Romanian
   Overview of changes in GLib 2.69.2
    * The `DBUS_SESSION_BUS_ADDRESS` environment variable is once more not used if
      the process is `AT_SECURE` (setuid/setgid/setcap); this change was previously
      applied and then reverted because it broke gnome-keyring (#2316)
    * Add `g_test_fail_printf()`, `g_test_skip_printf()`,
      `g_test_incomplete_printf()` helper functions for printing messages when tests
      end prematurely (work by Simon McVittie) (!2215)
    * Add portal implementation of `GPowerProfileMonitor` (work by
      Bastien Nocera) (!2222)
    * Bugs fixed:
      - #2316 Re-harden DBUS_SESSION_BUS_ADDRESS for AT_SECURE processes in GLib 2.70
      - #2343 Document explicitly refcount mgmt of source-object during GAsyncReadyCallbacks
      - #2454 Read past the end of buffer in g_win32_package_parser_enum_packages
      - #2456 Frequent test failure on FreeBSD: glib/tests/thread-pool.c:197:test_thread_pool_full: 'free_func_called' should be TRUE
      - !2157 tests: Add missing wakeup calls to gdbus-names test
      - !2165 docs: Mention the stable/unstable support version in README.md
      - !2211 Improve documentation of various TLS stuff
      - !2215 gtestutils: Add more convenience functions
      - !2216 tests: Fix error handling when testing gtestutils
      - !2222 gio: Add portal version of GPowerProfileMonitor
      - !2224 Docs: Mention that G_VA_COPY() must be followed by `va_end()`
      - !2225 build: Fix implicit declaration of function errors
      - !2226 Annotate the GString constructors
    * Translation updates:
      - Czech
      - Hebrew
      - Slovenian
      - Spanish
      - Swedish
   Overview of changes in GLib 2.69.1
    * Support categories in desktop notifications (`GNotification`)
      (work by Guido Günther) (#2446)
    * Add `GPowerProfileMonitor` for monitoring when to use less power (due to being
      on battery power, electricity being expensive or high-carbon, etc.)
      (work by Patrick Griffis, Bastien Nocera) (#2444)
    * Allow static names to be set for `GSource`s to avoid unnecessary string copies
      (work by Matthias Clasen) (!2196)
    * Bugs fixed:
      - #203 API: need g_module_open() variant with GError
      - #2058 win32: GPrivate can leak some objects
      - #2321 Add a GTypeFlag for final types
      - #2429 safe_fdwalk/safe_closefrom for Solaris 11.3/11.4
      - #2439 gio trash doesn't recognize existing trash directory in non-fs-root mount
      - #2446 Support `categories` for notifications
      - #2452 g_string_replace() loops 2**32 times when replacing empty string
      - !2177 gio/tests/g-file-info: don't assume million-in-one events don't happen
      - !2178 Clarify GValue documentation
      - !2179 Update GValue doc: How to use GBoxed with GValue
      - !2180 correctly use 3 parameters for close_range
      - !2181 gclosure: Fix the invoke() return_value annotation
      - !2182 glocalfileinfo: Fix usec/nsec confusion with filetimes on Windows
      - !2184 gspawn: Use CLOSE_RANGE_CLOEXEC if available
      - !2188 g_boxed_type_register_static, G_DEFINE_BOXED_TYPE: added correlating information
      - !2192 Fix more warnings
      - !2193 glib.supp: Expand match kinds for g_get_language_names() suppressions
      - !2194 Add GPowerProfileMonitor
      - !2195 Fix some test suite memory leaks
      - !2196 mainloop: Add g_source_set_static_name
      - !2197 GResource compiler: Prefix static [con|de]strutors with c_name
      - !2198 Port internal uses to use g_source_set_static_name()
      - !2200 Fix doc stanzas for GDataInputStream properties
      - !2201 Fix a Unicode typo
      - !2202 Document the stance on ID-based mainloop APIs
      - !2204 tests: Add a test for Unicode normalization
      - !2205 GWin32RegistryKey / GWin32AppInfo registry watch fixes
      - !2206 Adapt documentation to gi-docgen
      - !2210 GWin32AppInfo: Fix missing initialization
    * Translation updates:
      - Indonesian
      - Portuguese
      - Portuguese (Brazil)
      - Russian
      - Ukrainian

Signed-off-by: Adolf Belka <adolf.belka@ipfire.org>