libvirt: Update to version 11.4.0
- Update from version 10.10.0 to 11.4.0
- Update of rootfile
- Changelog
    11.4.0
      New features
        qemu: ppc64 POWER11 processor support
        Support for the recently released IBM POWER11 processor was added.
      Packaging changes
        All helper programs are now detected from $PATH during runtime
        All of the code was now converted to dynamically look up helper programs in
	 $PATH rather than doing the lookup at build time and then compiling in the
	 result.
        Programs mount, umount, mkfs, modprobe, rmmod, numad, dmidecode, ip, tc,
	 mdevctl, mm-ctl, iscsiadm, ovs-vsctl, pkttyagent, bhyveload, bhyvectl, bhyve,
	 ifconfig, vzlist, vzctl, vzmigrate, and the tools from the lvm suite
	 (vgchange, lvcreate, etc..) are now not needed during build and will still
	 work properly if placed in $PATH.
        This also ensures that libvirt works correctly on distros that are
	 transitioning /sbin into /bin and upgraded installations have a different
	 layout from fresh installations.
      Improvements
        virsh: Add option --no-pkttyagent
        That option suppresses registration of pkttyagent with polkitd.
        bhyve: support NVRAM configuration for UEFI firmwares
        The bhyve driver now supports specifying NVRAM store file, such as:
	        <os firmware='efi'>
	          <nvram/>
	        </os>
        qemu: Improve accuracy of FDC/floppy device support statement in capabilities XML
        The data is now based on the presence of the controller in qemu rather than
	 just a denylist of machine types where floppies not work.
      Bug fixes
        qemu: Fix failure when reverting to internal snapshots
        A regression in libvirt-11.2 and libvirt-11.3 prevents reverting to an
	 internal snapshot. Attempts to revert would produce the following error:
         error: operation failed: load of internal snapshot 'foo1' job failed: Device
	 'libvirt-1-format' is writable but does not support snapshots
         The only workaround is to avoid the broken versions.
        qemu: Fix virtqemud crash when resuming failed post-copy migration
         A regression introduced in libvirt-11.2.0 caused virtqemud on the destination
	 host to crash when trying to resume failed post-copy migration.
        qemu: Treat the queues configuration of virtio-net as guest ABI
         The queue count itself isn't a device frontend property but libvirt uses it to
	 calculate vectors option of the device which is a guest OS visible property,
	 thus queues must not change during migration. The ABI stability check now
	 handles this properly.
    11.3.0
      Removed features
        Support for AppArmor versions prior to 3.0.0 has been dropped.
      New features
        xen: Support configuration of <hyperv/> flags for Xen domains.
        The following flags are now configurable for Xen: vapic, synic, stimer,
	 frequencies, tlbflush and ipi.
        bhyve: Support virtio random number generator devices
        Domain XMLs can now include virtio random number generator devices. They are
	 configured with:
	        <rng model='virtio'>
	          <backend model='random'/>
	        </rng>
        bhyve: Support <interface type='network'>
        At the moment it doesn't provide any new features compared to
	 <interface type='bridge'>, but allows a more flexible configuration.
      Bug fixes
        cpu_map: Install Ampere-1 ARM CPU models
        The Ampere-1 CPU models added in the previous release were not properly
	 installed and thus every attempt to start an ARM domain with custom CPU
	 definition would fail.
        storage: Fix new volume creation
        No more errors occur when new storage volume is being created using virsh
	 vol-create with --validate option and/or virStorageVolCreateXML() with
	 VIR_VOL_XML_PARSE_VALIDATE flag.
        Don't spam logs with error about qemu-rdp when starting a qemu VM
        On hosts where the qemu-rdp binary is not installed a start of a VM would
	 cause an error such as
         error : qemuRdpNewForHelper:103 : 'qemu-rdp' is not a suitable qemu-rdp helper
	 name: No such file or directory
         to be logged in the system log. It is safe to ignore the error. The code was
	 fixed to avoid the message when probing for support.
        Fix libvirt daemon crash on failure to hotplug a disk into a qemu VM
        Some failures of disk hotplug could cause the libvirt daemon to crash due to a
	 bug when rolling back disk throttling filters.
    11.2.0
      Removed features
        Remove support for qemu-6.1 and older
        Libvirt now requires qemu-6.2 or newer based on our platform support policy.
      New features
        qemu: Add new 'image_format' parameter to virDomainSaveParams
        virDomainSaveParams now supports an image_format parameter for specifying the
	 save image format on a per-domain basis. The parameter accepts the same
	 values as the driver-wide save_image_format setting in qemu.conf. An image
	 format specified via virDomainSaveParams takes precedence over the
	 driver-wide setting.
        qemu: Added guest load averages to the output of virDomainGetGuestInfo
        This feature will be available with qemu guest agent 10.0 onwards.
        qemu: Add support for multiple iothreads for virtio-scsi controller
        It's now possible to map multiple iothreads to the virtio-scsi controller or
	 even map them to specific virtqueues similarly to the virtio-blk device
	 allowing for better performance in certain scenarios.
        qemu: integrate support for VM shutdown on host shutdown
        It is now possible to instruct the QEMU driver to automatically perform
	 managed save, graceful shutdown, or hard poweroff on running VMs, when a host
	 shutdown is requested. This feature is intended to eventually replace usage
	 of the libvirt-guests script. The new approach improves on the libvirt-guests
	 script, by proactively monitoring logind for a signal that a host shutdown
	 has been requested. It will initiate the chosen action on running guests
	 immediately, allowing shutdown inhibitors to be released sooner. The new
	 solution is also able to iteratively try multiple actions until one of them
	 succeeds in shutting down the VM.
        Since it must be mutually exclusive with the libvirt-guests script, this
	 feature currently requires a manual opt-in through editing of the
	 /etc/libvirt/qemu.conf configuration file. The libvirt-guests script must be
	 disabled before doing this.
        qemu: Add 'sparse' as a new save image format
        QEMU's file migration has been supplemented with the new stream format
	 mapped-ram, where RAM pages are mapped directly to offsets in the migration
	 file. mapped-ram is now supported by augmenting the existing save image
	 formats with the sparse format.
        qemu: Add support for parallel save/restore
        The sparse image format can support reading and writing by multiple channels.
	 virDomainSaveParams and virDomainRestoreParams now support specifying the
	 number of IO channels used for parallel save and restore. Using multiple
	 channels can reduce the time required to save and restore domains.
        virsh: Introduce new hypervisor-cpu-models command
        Added a new virsh command hypervisor-cpu-models. The command pulls from the
	 existing domcapabilities XML and uses xpath to parse CPU model strings. By
	 default, only models reported as usable by the hypervisor on the host system
	 are printed. A user may specify --all to also print models which are not
	 supported on the host.
        qemu: Introduce os/shim element
        For secure boot environments where <loader/> is signed, it may be unfeasible
	 to keep the binary up to date (esp. when revoking certificates contained
	 within). To address that, new <shim/> element is introduced which allows
	 hypervisor to side load another UEFI binary, which can then contain new
	 certification authorities and/or list of revocations.
        ch: Enable SEV SNP support
        Cloud Hypervisor guests can be now started with SEV SNP enabled.
        qemu: Support for Block Disk Along with Throttle Filters
        Introduce support for multiple throttle groups per block disk in QEMU,
	 enhancing I/O control and performance optimization. This update builds on the
	 existing throttling functionality by allowing more granular control with the
	 ability to assign different throttle groups to multiple block devices,
	 improving shared throttling across devices.
      Improvements
        qemu: Improved guest agent corner case error reporting
        The APIs using the guest agent now report two specific error codes aimed at
	 helping management applications/users to differentiate between timeout while
	 libvirt was synchronizing with the guest agent and timeout after a command
	 was already sent.
        The new error codes are VIR_ERR_AGENT_COMMAND_TIMEOUT and
	 VIR_ERR_AGENT_COMMAND_FAILED.
        qemu: Use common check for shared memory use for vhost-user network devices
        Historically libvirt printed only a warning if the vhost-user network was
	 misconfigured. Since we enforce proper configuration for other device types
	 using vhost-user it is now enforced also for network devices and prints an
	 actual error on misconfiguration.
        Introduce constants for discoverability of entries in bulk stats APIs
        Libvirt introduced constants exposed by our API description XML which allows
	 discoverability of new entries in typed parameter names returned by
	 virConnectGetAllDomainStats, virDomainListGetStats, and virDomainGetGuestInfo.
        qemu: Reflect MAC address change in live domain XML
        When a guest changes MAC address on one of its vNICs the new MAC address is
	 now visible in the live XML under currentAddress attribute of <mac/> element.
	 At the same time, VIR_DOMAIN_EVENT_ID_NIC_MAC_CHANGE event is emitted so that
	 management applications can update their internal state.
      Bug fixes
        qemu: attach virtio-mem with CCW address
        Attaching a virtio-mem device on s390 without an address type now gets a
	 default type CCW address assigned. A specified CCW address is now used for
	 the virtio-mem device instead of getting overwritten by a PCI address.
        ch: Various memory leak fixes
        There were some memory leaks identified in the Cloud Hypervisor driver. They
	 are fixed now.
    11.1.0
      Packaging changes
        De-modularize the 'fs' storage file backend
        The storage file backend for local files uses only code which we compile into
	 the internal libraries anyways so there's no point in having it as a loadable
	 module. The storage-file/libvirt_storage_file_fs.so module no longer exists
	 and its functionality is embedded directly.
      Removed features
        vbox: removed support for version 6.1 APIs
        Libvirt no longer supports use of VirtualBox 6.1 since this version reached
	 its end of life on 2024/01.
      New features
        nodedev: Support ccwgroup based qeth devices
        CCW group devices are devices that use multiple subchannels on the mainframe's
	 channel subsystem. A qeth group device maps to subchannels and their
	 corresponding device numbers and device bus-IDs. The ccwgroup device nodes
	 are placed besides the subchannel nodes under computer and list the group
	 members within a new ccwgroup capability. A new capability ccwgroup_member is
	 added into capability ccw to represent a device membership to a ccwgroup.
	 Filters are added to find ccwgroups as well as ccwgroup members.
        ch: Support handling events from cloud-hypervisor
        The ch driver now supports handling events from the cloud-hypervisor. Events
	 include VM lifecyle operations such as shutdown, pause, resume, etc. Libvirt
	 will now read these events and take actions such as updating domain state, etc.
        Introduce virtio-mem <memory/> model for s390 guests
        The virtio-mem model of <memory/> device can now be used with s390 guests.
        Support using passt as the backend for interface type='vhostuser'
        The combination of vhostuser transport with passt as the backend provides high
	 performance, fully featured networking without the need for libvirt or QEMU
	 to have any elevated privileges or capabilities. Configuration and features
	 are identical to the configuration for type='user' with the passt backend.
      Improvements
        qemu: I/O error messages can be queried via virDomainGetMessages()
        The qemu hypervisor driver now preserves the last I/O error message along with
	 the timestamp when it was recorded and preserves it to be queried via
	 virDomainGetMessages().
      Bug fixes
        tools: ssh-proxy: Check if domain is running before connecting to it
        If domain is not running but has a static CID configured for its VSOCK then
	 the ssh-proxy parsed it anyways. This may have resulted in mistakenly
	 connecting to a different domain. Domain status is checked before parsing its
	 CID.
        apparmor: Allow SGX if configured
        If domain has <memory model='sgx-epc'\> configured then libvirt now adds
	 corresponding devices into a per-domain profile so that AppArmor does not
	 deny QEMU access to them.
        qemu: Fix crash when starting a domain on a host with unknown host CPU
        On hosts where we cannot detect a host CPU model (mostly aarch64 hosts)
	 starting a domain with a custom CPU model caused a crash of virtqemud.
        The bug was introduced in libvirt-10.9.0
    11.0.0
      New features
        network/qemu/lxc: support vlans on standard Linux host bridges
        The network, qemu, and lxc drivers now support (using the <vlan> subelement)
	 vlan tagging and trunking on network interfaces connected to a standard Linux
	 host bridge.
        qemu: Add support for direct and extended tlbflush features
        Domains can now utilise more tlbflush hyperv features.
      Improvements
        ch: Enable user aliases
        User can now specify custom aliases for devices in domain XML
        qemu: Grab a QUERY job when formatting domain XML
        Under some specific conditions it might have happened that domain XML did not
	 contain runtime information or returned an XML that's in process of changing
	 (e.g. by a thread that's hotplugging a device). Formatting domain XML now
	 serializes properly with other threads.
        virtiofs: Allow read only mode
        The <filesystem/> with virtiofsd backend can now use <readonly/> tag to export
	 underlying filesystem in read only mode.
        qemu: allow migration of vGPU from mdev device <-> SRIOV VF device
        Some GPU vendors are switching from using vGPUs creating using mdev and
	 identified with a uuid, to vGPUs created as SRIOV VFs and identified by their
	 PCI address, and want to support live migration from a host using one type of
	 vGPU to the other type. This is now possible.
      Bug fixes
        qemu: tpm: do not update profile name for transient domains
        Fix a possible crash when starting a transient domain which was introduced in
	 the previous release.
        qemu: Fix snapshot to not delete disk image with internal snapshot
        When a VM has internal snapshot that is parent to external snapshot and user
	 reverts to the internal snapshot and deletes the external snapshot libvirt
	 would delete the disk image containing the internal snapshot. This would
	 result in data loss.
        qemu: Do not format invalid XML with hyperv features in passthrough mode
        When hyperv features were specified together with mode="passthrough" libvirt
	 parsed and formatted such features in the domain XML even though they were
	 not used at all, resulting in XML that is not valid based on our schema. This
	 is now fixed by not parsing any specified features when the passthrough mode
	 is used.
        qemu: Fix a crash when starting a domain with ovs bridge and QOS
        cpu: Add missing -v1 variants for CPU models
        Some CPU models (mostly old ones) were missed when versioned CPU model names
	 were introduced in the previous release.
        qemu: Fix false error when recovering failed post-copy migration
        In some cases libvirt would report a failure to recover post-copy migration
	 even though the recovery started just fine and migration would eventually
	 successfully finish.

Signed-off-by: Adolf Belka <adolf.belka@ipfire.org>
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>