gdb: Update to 10.2
- Update from 10.1 to 10.2
- Update rootfiles
- Changelog
   GDB 10.2 brings the following fixes and enhancements over GDB 10.1:
    * PR remote/26614 (AddressSanitizer: heap-use-after-free of extended_remote_target in remote_async_inferior_event_handler)
    * PR gdb/26828 (SIGSEGV in follow_die_offset dwarf2/read.c:22950)
    * PR gdb/26861 (internal-error: void target_mourn_inferior(ptid_t): Assertion `ptid == inferior_ptid' failed. OS: Mac OSX Catalina; Compiler: GCC; Language: C)
    * PR gdb/26876 (gdb error: internal-error: Unknown CFA rule when debugging the linux kernel with qemu)
    * PR breakpoints/26881 (infrun.c:6384: internal-error: void process_event_stop_test(execution_control_state*): Assertion `ecs->event_thread->control.exception_resume_breakpoint != NULL' failed)
    * PR gdb/26901 (Array subscript fails with flexible array member without size)
    * PR tui/26973 (gdb crashes when not including the status window in a new layout)
    * PR python/26974 (Wrong Value.format_string docu for static members argument)
    * PR breakpoints/27009 ([s390] GDB branches randomly for BC instruction while displaced stepping)
    * PR tdep/27015 (ARC: "eret" value is collected from the wrong data in register cache)
    * PR backtrace/27147 ([GNU/Linux, sparc64] GDB is unable to print full stack trace (got "previous frame inner to this frame" errors))
    * PR rust/27194 (put rust demangler on 10.x branch)
    * PR threads/27239 (gdb/cp-support.c:1619:(.text+0x5502): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `TLS init function for thread_local_segv_handler')
    * PR breakpoints/27330 (nextoverthrow.exp FAILs on arm-none-eabi)
    * PR symtab/27333 ([dwarf-5] abort on unhandled DW_TAG_type_unit in process_psymtab_comp_unit)
    * PR fortran/27341 ([dwarf-5] FAIL: gdb.fortran/function-calls.exp: p derived_types_and_module_calls::pass_cart_nd(c_nd))
    * PR tdep/27369 (ARC: Stepping over atomic instruction sequences loops infinitely)
    * PR build/27385 (Cannot compile arc.c with gcc-4.8 (error: no matching function for call to 'std::pair...'))
    * PR gdb/27435 (Attach on solaris segfaults GDB)
    * PR build/27535 (amd64-linux-siginfo.c fails to compile after updating to glibc-2.33 headers)
    * PR build/27536 (aarch64-linux-hw-point.c fails to compile after updating to glibc-2.33)
    * PR symtab/27541 (gdb crashes on "file -readnow")
    * PR gdb/27750 (local variables have wrong address and values on sparc64)
    * PR varobj/27757 (-var-list-children coredump)

Signed-off-by: Adolf Belka <adolf.belka@ipfire.org>
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>